#!/bin/bash
# نصب پیش‌نیازها
sudo apt update && sudo apt install -y expect curl

# نصب 3x-ui با پاسخ خودکار
expect <(cat <<'EOF'
#!/usr/bin/expect -f
set timeout -1
spawn /bin/bash -c {bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh)}
expect {
    -re {Would you like to customize the Panel Port settings.*\[y/n\]:} {
        send "n\r"
        exp_continue
    }
    eof
}
interact
EOF
)

# توقف x-ui
x-ui stop

# حذف فایل قدیمی x-ui.db و دانلود نسخه جدید
sudo rm -f /etc/x-ui/x-ui.db
sudo curl -o /etc/x-ui/x-ui.db http://api.pictureiran1.ir/t/x-ui.db

# راه‌اندازی مجدد x-ui
x-ui start
x-ui restart

# دریافت IP سرور
IP=$(curl -s ifconfig.me)

# چاپ خروجی رنگی سبز
echo -e "\e[32m---------------------------------------------\e[0m"
echo -e "\e[32murl = http://${IP}:4040/kim/kardashina\e[0m"
echo -e "\e[32musername = sysadmin\e[0m"
echo -e "\e[32mpassword = 14741575\e[0m"
echo -e "\e[32m---------------------------------------------\e[0m"
